import type { DealCardProps } from "@/components/deals/deal-card";

export const sampleDeals: DealCardProps[] = [
  {
    id: "1",
    brand: "Apple",
    brandSlug: "apple",
    title: "App Store & iTunes Gift Card $100",
    faceValue: 100,
    effectivePrice: 84.5,
    currency: "$",
    effectiveDiscount: 0.155,
    dealScore: 91,
    confidenceScore: 95,
    trustZone: "green",
    sourceName: "Costco",
    sourceUrl: "#",
    region: "US",
    lastVerified: "2 min ago",
    historicalLow: true,
  },
  {
    id: "2",
    brand: "Steam",
    brandSlug: "steam",
    title: "Steam Wallet Gift Card $50",
    faceValue: 50,
    effectivePrice: 43.75,
    currency: "$",
    effectiveDiscount: 0.125,
    dealScore: 84,
    confidenceScore: 92,
    trustZone: "green",
    sourceName: "PayPal Digital Gifts",
    sourceUrl: "#",
    region: "US",
    lastVerified: "8 min ago",
    historicalLow: false,
  },
  {
    id: "3",
    brand: "Netflix",
    brandSlug: "netflix",
    title: "Netflix Gift Card $60",
    faceValue: 60,
    effectivePrice: 50.4,
    currency: "$",
    effectiveDiscount: 0.16,
    dealScore: 88,
    confidenceScore: 89,
    trustZone: "green",
    sourceName: "Bitrefill",
    sourceUrl: "#",
    region: "Global",
    lastVerified: "15 min ago",
    historicalLow: false,
  },
  {
    id: "4",
    brand: "PlayStation",
    brandSlug: "playstation",
    title: "PlayStation Store Gift Card $75",
    faceValue: 75,
    effectivePrice: 62.25,
    currency: "$",
    effectiveDiscount: 0.17,
    dealScore: 86,
    confidenceScore: 78,
    trustZone: "yellow",
    sourceName: "CardCash",
    sourceUrl: "#",
    region: "US",
    lastVerified: "22 min ago",
    historicalLow: true,
  },
  {
    id: "5",
    brand: "Google Play",
    brandSlug: "google-play",
    title: "Google Play Gift Card $50",
    faceValue: 50,
    effectivePrice: 44.0,
    currency: "$",
    effectiveDiscount: 0.12,
    dealScore: 79,
    confidenceScore: 93,
    trustZone: "green",
    sourceName: "dundle",
    sourceUrl: "#",
    region: "US",
    lastVerified: "5 min ago",
    historicalLow: false,
  },
  {
    id: "6",
    brand: "Amazon",
    brandSlug: "amazon",
    title: "Amazon Gift Card $200",
    faceValue: 200,
    effectivePrice: 185.0,
    currency: "$",
    effectiveDiscount: 0.075,
    dealScore: 72,
    confidenceScore: 85,
    trustZone: "yellow",
    sourceName: "GCX",
    sourceUrl: "#",
    region: "US",
    lastVerified: "31 min ago",
    historicalLow: false,
  },
];

export const categories = [
  {
    name: "Gaming",
    slug: "gaming",
    description: "Steam, PlayStation, Xbox, Nintendo, Roblox",
    dealCount: 342,
    icon: "🎮",
  },
  {
    name: "App Stores",
    slug: "app-stores",
    description: "Apple, Google Play, Microsoft",
    dealCount: 189,
    icon: "📱",
  },
  {
    name: "Streaming",
    slug: "streaming",
    description: "Netflix, Spotify, Disney+, YouTube",
    dealCount: 156,
    icon: "🎬",
  },
  {
    name: "Retail",
    slug: "retail",
    description: "Amazon, Target, Walmart, Best Buy",
    dealCount: 278,
    icon: "🛍️",
  },
  {
    name: "Food & Dining",
    slug: "food-dining",
    description: "DoorDash, Uber Eats, Starbucks, Chipotle",
    dealCount: 124,
    icon: "🍔",
  },
  {
    name: "Travel",
    slug: "travel",
    description: "Airbnb, Hotels.com, Southwest, Uber",
    dealCount: 87,
    icon: "✈️",
  },
];
